server:
    port: 8801

spring:
    datasource:
        #driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:3306/vodafone
        username: root
        password: password

    jpa:
        hibernate:
            ddl-auto: update

        show_sql: true
        database: mysql